### ISSUE TITLE
'64bit Amazon Linux 2014.09 v1.1.0 running Tomcat 7 Java 7' is not a valid solution stack name

### ISSUE THREAD

**Issue by reedlaw** [ThoughtWorksStudios/eb_deployer#46]
I get this error running `eb_deploy -p app.zip -e dev`. My `eb_deployer.yml` is unchanged.
```
/home/reed/.gem/ruby/2.2.0/gems/eb_deployer-0.5.2/lib/eb_deployer/eb_environment.rb:106:in `validate_solutions_stack': '64bit Amazon Linux 2014.09 v1.1.0 ru
nning Tomcat 7 Java 7' is not a valid solution stack name, available solution stack names are: 64bit Amazon Linux 2015.03 v1.4.3 running Node.js, 64bit Amaz
on Linux 2014.03 v1.1.0 running Node.js, 32bit Amazon Linux 2014.03 v1.1.0 running Node.js, 64bit Amazon Linux 2015.03 v1.4.3 running PHP 5.6, 64bit Amazon 
Linux 2015.03 v1.4.3 running PHP 5.5, 64bit Amazon Linux 2015.03 v1.4.3 running PHP 5.4, 64bit Amazon Linux 2014.03 v1.1.0 running PHP 5.5, 64bit Amazon Lin
ux 2014.03 v1.1.0 running PHP 5.4, 32bit Amazon Linux 2014.03 v1.1.0 running PHP 5.5, 32bit Amazon Linux 2014.03 v1.1.0 running PHP 5.4, 64bit Amazon Linux 
running PHP 5.3, 32bit Amazon Linux running PHP 5.3, 64bit Amazon Linux 2015.03 v1.4.3 running Python 3.4, 64bit Amazon Linux 2015.03 v1.4.3 running Python 
2.7, 64bit Amazon Linux 2015.03 v1.4.3 running Python, 64bit Amazon Linux 2014.03 v1.1.0 running Python 2.7, 64bit Amazon Linux 2014.03 v1.1.0 running Pytho
n, 32bit Amazon Linux 2014.03 v1.1.0 running Python 2.7, 32bit Amazon Linux 2014.03 v1.1.0 running Python, 64bit Amazon Linux running Python, 32bit Amazon L
inux running Python, 64bit Amazon Linux 2015.03 v1.4.3 running Ruby 2.2 (Puma), 64bit Amazon Linux 2015.03 v1.4.3 running Ruby 2.2 (Passenger Standalone), 6
4bit Amazon Linux 2015.03 v1.4.3 running Ruby 2.1 (Puma), 64bit Amazon Linux 2015.03 v1.4.3 running Ruby 2.1 (Passenger Standalone), 64bit Amazon Linux 2015
.03 v1.4.3 running Ruby 2.0 (Puma), 64bit Amazon Linux 2015.03 v1.4.3 running Ruby 2.0 (Passenger Standalone), 64bit Amazon Linux 2015.03 v1.4.3 running Rub
y 1.9.3, 64bit Amazon Linux 2015.03 v1.4.1 running Ruby 2.2 (Puma), 64bit Amazon Linux 2015.03 v1.4.1 running Ruby 2.2 (Passenger Standalone), 64bit Amazon 
Linux 2015.03 v1.4.1 running Ruby 2.1 (Puma), 64bit Amazon Linux 2015.03 v1.4.1 running Ruby 2.1 (Passenger Standalone), 64bit Amazon Linux 2015.03 v1.4.1 r
unning Ruby 2.0 (Puma), 64bit Amazon Linux 2015.03 v1.4.1 running Ruby 2.0 (Passenger Standalone), 64bit Amazon Linux 2015.03 v1.4.1 running Ruby 1.9.3, 64b
it Amazon Linux 2014.03 v1.1.0 running Ruby 2.1 (Puma), 64bit Amazon Linux 2014.03 v1.1.0 running Ruby 2.1 (Passenger Standalone), 64bit Amazon Linux 2014.0
3 v1.1.0 running Ruby 2.0 (Puma), 64bit Amazon Linux 2014.03 v1.1.0 running Ruby 2.0 (Passenger Standalone), 64bit Amazon Linux 2014.03 v1.1.0 running Ruby 
1.9.3, 32bit Amazon Linux 2014.03 v1.1.0 running Ruby 1.9.3, 64bit Amazon Linux 2015.03 v1.4.3 running Tomcat 8 Java 8, 64bit Amazon Linux 2015.03 v1.4.3 ru
nning Tomcat 7 Java 7, 64bit Amazon Linux 2015.03 v1.4.3 running Tomcat 7 Java 6, 64bit Amazon Linux 2014.03 v1.1.0 running Tomcat 7 Java 7, 64bit Amazon Li
nux 2014.03 v1.1.0 running Tomcat 7 Java 6, 32bit Amazon Linux 2014.03 v1.1.0 running Tomcat 7 Java 7, 32bit Amazon Linux 2014.03 v1.1.0 running Tomcat 7 Ja
va 6, 64bit Amazon Linux running Tomcat 7, 64bit Amazon Linux running Tomcat 6, 32bit Amazon Linux running Tomcat 7, 32bit Amazon Linux running Tomcat 6, 64
bit Windows Server Core 2012 R2 running IIS 8.5, 64bit Windows Server 2012 R2 running IIS 8.5, 64bit Windows Server 2012 running IIS 8, 64bit Windows Server
 2008 R2 running IIS 7.5, 64bit Amazon Linux 2015.03 v1.4.3 running Docker 1.6.2, 64bit Amazon Linux 2015.03 v1.4.3 running Multi-container Docker 1.6.2 (Ge
neric), 64bit Debian jessie v1.4.3 running GlassFish 4.1 Java 8 (Preconfigured - Docker), 64bit Debian jessie v1.4.3 running GlassFish 4.0 Java 7 (Preconfig
ured - Docker), 64bit Debian jessie v1.4.3 running Go 1.4 (Preconfigured - Docker), 64bit Debian jessie v1.4.3 running Go 1.3 (Preconfigured - Docker), 64bi
t Debian jessie v1.4.3 running Python 3.4 (Preconfigured - Docker) (RuntimeError)                                                                          
        from /home/reed/.gem/ruby/2.2.0/gems/eb_deployer-0.5.2/lib/eb_deployer/eb_environment.rb:81:in `create_eb_env'
        from /home/reed/.gem/ruby/2.2.0/gems/eb_deployer-0.5.2/lib/eb_deployer/eb_environment.rb:27:in `deploy'
        from /home/reed/.gem/ruby/2.2.0/gems/eb_deployer-0.5.2/lib/eb_deployer/deployment_strategy/blue_green.rb:18:in `deploy'
        from /home/reed/.gem/ruby/2.2.0/gems/eb_deployer-0.5.2/lib/eb_deployer/default_component.rb:16:in `deploy'
        from /home/reed/.gem/ruby/2.2.0/gems/eb_deployer-0.5.2/lib/eb_deployer/environment.rb:32:in `block in deploy'
        from /home/reed/.gem/ruby/2.2.0/gems/eb_deployer-0.5.2/lib/eb_deployer/environment.rb:31:in `each'
        from /home/reed/.gem/ruby/2.2.0/gems/eb_deployer-0.5.2/lib/eb_deployer/environment.rb:31:in `deploy'
        from /home/reed/.gem/ruby/2.2.0/gems/eb_deployer-0.5.2/lib/eb_deployer.rb:212:in `deploy'
        from /home/reed/.gem/ruby/2.2.0/gems/eb_deployer-0.5.2/lib/eb_deployer.rb:255:in `cli'
        from /home/reed/.gem/ruby/2.2.0/gems/eb_deployer-0.5.2/bin/eb_deploy:11:in `<top (required)>'
        from /home/reed/.gem/ruby/2.2.0/bin/eb_deploy:23:in `load'
        from /home/reed/.gem/ruby/2.2.0/bin/eb_deploy:23:in `<main>'
```

**Comment by wpc** [comment]
Seems AWS has retried old solution stack. Please change 'solution_stack_name' option to a recent solution stack version in config file.

Choose from following if you are in java or jruby:
64bit Amazon Linux 2015.03 v1.4.3 running Tomcat 8 Java 8
64bit Amazon Linux 2015.03 v1.4.3 running Tomcat 7 Java 7
64bit Amazon Linux 2015.03 v1.4.3 running Tomcat 7 Java 6
64bit Amazon Linux 2014.03 v1.1.0 running Tomcat 7 Java 7
64bit Amazon Linux 2014.03 v1.1.0 running Tomcat 7 Java 6
32bit Amazon Linux 2014.03 v1.1.0 running Tomcat 7 Java 7
32bit Amazon Linux 2014.03 v1.1.0 running Tomcat 7 Java 6

-- wpc

**Comment by wpc** [comment]
I will close this issue and leave a todo item for clearer message when solution stack not supported.
